### ISSUE TITLE
Specify minimal SDL2 version required

### ISSUE THREAD

**Issue by etam** [skyjake/lagrange#768]
I noticed, that for an old system lagrange fails to build, because

```
[   74s] /home/abuild/rpmbuild/BUILD/lagrange-1.20.2/src/ui/gamepad.c:102:13: error: implicit declaration of function 'SDL_GameControllerGetType'; did you mean 'SDL_GameControllerGetAxis'? [-Werror=implicit-function-declaration]
```

According to https://wiki.libsdl.org/SDL2/SDL_GameControllerGetType the missing function is available since SDL 2.0.12.

It would be best if the minimal required version was specified in cmake.

**Comment by skyjake** [comment]
Yes, worth documenting.

Does setting `ENABLE_GAMEPAD` to `NO` allow it to build?

**Comment by etam** [comment]
With ENABLE_GAMEPAD=NO it still fails to build with SDL 2.0.8:
```
[   39s] /home/abuild/rpmbuild/BUILD/lagrange-1.20.3/src/ui/window.c:1616:14: error: 'SDL_TEXTEDITING_EXT' undeclared (first use in this function); did you mean 'SDL_TEXTEDITING'?
[   39s]          case SDL_TEXTEDITING_EXT:
[   39s]               ^~~~~~~~~~~~~~~~~~~
[   39s]               SDL_TEXTEDITING
[   39s] /home/abuild/rpmbuild/BUILD/lagrange-1.20.3/src/ui/window.c:1616:14: note: each undeclared identifier is reported only once for each function it appears in
[   39s] /home/abuild/rpmbuild/BUILD/lagrange-1.20.3/src/ui/window.c:1617:24: error: 'SDL_Event {aka const union SDL_Event}' has no member named 'editExt'; did you mean 'edit'?
[   39s]              return ev->editExt.windowID;
[   39s]                         ^~~~~~~
[   39s]                         edit
```

This raises the minimal SDL version to 2.0.22

**Comment by skyjake** [comment]
The TEXTEDITING code / InputWidget preedit CJK IME support could be made conditional behind an SDL version check. This code was only added in the very latest 1.20.3 release, though. You could test with 1.20.2 to see if there are other version compatibility issues.

**Comment by etam** [comment]
Lagrange 1.20.2 with ENABLE_GAMEPAD=NO and SDL 2.0.8 built successfully.

**Comment by skyjake** [comment]
Thanks for testing it out. I'll see about adding some ifdefs for the IME code.

**Comment by gapan** [comment]
I think I stumbled on the same (or similar) issue, only using SDL 2.0.20. For me it originally stops at:

```
/home/gapan/lagrange/src/lagrange-1.20.4/src/ui/gamepad.c: In function ‘ticker_Gamepad_’:
/home/gapan/lagrange/src/lagrange-1.20.4/src/ui/gamepad.c:190:18: error: ‘SDL_MouseWheelEvent’ has no member named ‘mouseX’
  190 |                 .mouseX    = d->pointer.x,
      |                  ^~~~~~
/home/gapan/lagrange/src/lagrange-1.20.4/src/ui/gamepad.c:191:18: error: ‘SDL_MouseWheelEvent’ has no member named ‘mouseY’
  191 |                 .mouseY    = d->pointer.y,
      |                  ^~~~~~
gmake[2]: *** [CMakeFiles/app.dir/build.make:552: CMakeFiles/app.dir/src/ui/gamepad.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/app.dir/all] Error 2
```

Setting `ENABLE_GAMEPAD=NO` proceeds further, only to error out at the same `SDL_TEXTEDITING_EXT` as above. Version 1.20.2 compiles with `ENABLE_GAMEPAD=NO`.
