### ISSUE TITLE
lagrange 1.19.0 doesn't build with the_Foundation v1.9.1 (missing rangeFrom_String)

### ISSUE THREAD

**Issue by norayr** [skyjake/lagrange#743]
On my gentoo, with my overlay, i tried to build my ebuild of lagrange-1.19.0 and

```
/var/tmp/portage/net-client/lagrange-1.19.0/work/lagrange-1.19.0/src/ui/sidebarwidget.c: In function ‘cmpGopherStructureUrl_’:
/var/tmp/portage/net-client/lagrange-1.19.0/work/lagrange-1.19.0/src/ui/sidebarwidget.c:458:28:
  error: implicit declaration of function ‘rangeFrom_String’; did you mean ‘range_String’? [-Wimplicit-function-declaration]
  458 |     const iRangecc sel1  = rangeFrom_String(a, start + 1);
      |                            ^~~~~~~~~~~~~~~~
      |                            range_String
/var/tmp/portage/net-client/lagrange-1.19.0/work/lagrange-1.19.0/src/ui/sidebarwidget.c:458:28:
  error: invalid initializer
/var/tmp/portage/net-client/lagrange-1.19.0/work/lagrange-1.19.0/src/ui/sidebarwidget.c:459:28:
  error: invalid initializer
  459 |     const iRangecc sel2  = rangeFrom_String(b, start + 1);

```

Looks like Lagrange 1.19.0 requires a post-1.9.1 the_Foundation

I was able to build Lagrange 1.19.0 with my ebuild that emerges the_Foundation from git, of latest version.

So I personally have no problem, just want to let you know about this.

**Comment by skyjake** [comment]
Ah yes, forgot to tag the library version. I've now tagged the_Foundation v1.10.0 and will make that the required version  in Lagrange v1.19.1.
